### ISSUE TITLE
Can't import plugin into Jython

### ISSUE THREAD

**Issue by HarrisNami** [fiji/Cell_Counter#5]
Hello,

I am writing a script in Jython that is trying to make use of the Cell Counter plugin commands without actually using the user interface (so that the process is automated for a lot of images). I am having trouble with simply importing the plugin. I came across the plugins.config file which shows the pathway for importation as this: sc.fiji.cellCounter.Cell_Counter

However I am getting the error “No module named cellCounter” while running the import as:
from sc.fiji.cellCounter.Cell_Counter import CellCounter.

I am unsure if I am doing something wrong in the syntax and if there is something more I should be writing.

Any help would be appreciated!

Thanks,
Harris

**Comment by imagejan** [comment]
You asked the [same question](https://forum.image.sc/t/importing-cellcounter-plugin-in-jython-script/32922?u=imagejan) on the forum and got a helpful reply there already. Let's keep the discussion on the forum, such that others can more easily find it.
